name: user_repository
description: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  review_repository:
    path: ../review_repository
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_core: ^2.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true