name: giventake
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0

  firebase_core: ^2.25.4

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.3

  user_repository:
    path: packages/user_repository
  request_repository:
    path: packages/request_repository
  product_repository:
    path: packages/product_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_slnt,wght.ttf
          weight: 400
  uses-material-design: true
  assets:
    - assets/
