name: giventake
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.15.8
  firebase_core: ^2.25.4
  uuid: ^4.4.0
  firebase_auth: ^4.4.0

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.3
  flutter_rating_bar: ^4.0.0

  user_repository:
    path: packages/user_repository
  request_repository:
    path: packages/request_repository
  product_repository:
    path: packages/product_repository
  review_repository:
    path: packages/review_repository
  fake_cloud_firestore: ^2.5.1
  google_sign_in_mocks: ^0.3.0
  firebase_auth_mocks: ^0.13.0
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_slnt,wght.ttf
          weight: 400
  uses-material-design: true
  assets:
    - assets/
