// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDfhLtLT1Eg9sAHeP57QwHREI0LaUw_c',
    appId: '1:601196658289:web:7f061a27b591491c49e5d0',
    messagingSenderId: '601196658289',
    projectId: 'giventake-54b96',
    authDomain: 'giventake-54b96.firebaseapp.com',
    storageBucket: 'giventake-54b96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY4cfEmx58PuQJpEmxfjvkgrYskaFPmdA',
    appId: '1:601196658289:android:1a4489815930e00949e5d0',
    messagingSenderId: '601196658289',
    projectId: 'giventake-54b96',
    storageBucket: 'giventake-54b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-8nL7sqpKotrJtudTbdpjCplNTgZIlTY',
    appId: '1:601196658289:ios:b86dc41200e736f949e5d0',
    messagingSenderId: '601196658289',
    projectId: 'giventake-54b96',
    storageBucket: 'giventake-54b96.appspot.com',
    iosBundleId: 'com.example.giventake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-8nL7sqpKotrJtudTbdpjCplNTgZIlTY',
    appId: '1:601196658289:ios:f3f08b6c148a70f649e5d0',
    messagingSenderId: '601196658289',
    projectId: 'giventake-54b96',
    storageBucket: 'giventake-54b96.appspot.com',
    iosBundleId: 'com.example.giventake.RunnerTests',
  );
}
